version: '3'

services:
  mariadb:
    container_name: pw-database
    build: .
    restart: on-failure
    ports:
      - 0.0.0.0:3306:3306
    environment:
      MYSQL_DATABASE: "pw"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "secret"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"

  adminer:
    image: adminer
    restart: always
    ports:
      - 0.0.0.0:8888:8080